import Foundation
import rNews

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

class FakeDocumentationUseCase : DocumentationUseCase {
    init() {
    }

    private(set) var htmlForDocumentCallCount : Int = 0
    var htmlForDocumentStub : ((Document) -> (String?))?
    private var htmlForDocumentArgs : Array<(Document)> = []
    func htmlForDocumentReturns(stubbedValues: (String?)) {
        self.htmlForDocumentStub = {(document: Document) -> (String?) in
            return stubbedValues
        }
    }
    func htmlForDocumentArgsForCall(callIndex: Int) -> (Document) {
        return self.htmlForDocumentArgs[callIndex]
    }
    func htmlForDocument(document: Document) -> (String?) {
        self.htmlForDocumentCallCount += 1
        self.htmlForDocumentArgs.append((document))
        return self.htmlForDocumentStub!(document)
    }

    static func reset() {
    }
}
