disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - variable_name
  - closing_brace
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - Tethys
  - TethysKit
  - Tethys_Mac
  - TethysKit_Mac
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - TethysSpecs
  - TethysKitSpecs
  - TethysKit_MacSpecs
# parameterized rules can be customized from this configuration file
line_length:
  - 120
  - 200
function_body_length:
  - 60
  - 100
# parameterized rules are first parameterized as a warning level, then error level.
type_body_length:
  - 400 # warning
  - 600 # error
