@testable import rNewsKit

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

class FakeDatabaseMigrator : DatabaseMigratorType {
    init() {
    }

    private(set) var migrateCallCount : Int = 0
    private var migrateArgs : Array<(DataService, DataService, Void -> Void)> = []
    func migrateArgsForCall(callIndex: Int) -> (DataService, DataService, Void -> Void) {
        return self.migrateArgs[callIndex]
    }
    func migrate(from: DataService, to: DataService, finish: Void -> Void) -> (Void) {
        self.migrateCallCount++
        self.migrateArgs.append((from, to, finish))
    }

    private(set) var deleteEverythingCallCount : Int = 0
    private var deleteEverythingArgs : Array<(DataService, Void -> Void)> = []
    func deleteEverythingArgsForCall(callIndex: Int) -> (DataService, Void -> Void) {
        return self.deleteEverythingArgs[callIndex]
    }
    func deleteEverything(database: DataService, finish: Void -> Void) {
        self.deleteEverythingCallCount++
        self.deleteEverythingArgs.append((database, finish))
    }

    static func reset() {
    }
}
