# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.51.0"

default_platform :ios


platform :ios do
  desc 'Sets up (usually for CI)'
  lane :setup do
    match(type: 'development', app_identifier: 'com.rachelbrindle.RSSClient', readonly: true)
    match(type: 'appstore', app_identifier: 'com.rachelbrindle.RSSClient', readonly: true)
    carthage(platform: 'iOS')
  end

  desc 'Bumps version'
  lane :bump_version do
    increment_build_number(xcodeproj: 'RSSClient.xcodeproj', build_number: `git rev-parse --short HEAD`)
    commit_version_bump(xcodeproj: 'RSSClient.xcodeproj', force: true)
  end

  desc 'Pushes'
  lane :push do
    increment_build_number(xcodeproj: 'RSSClient.xcodeproj')
    commit_version_bump(xcodeproj: 'RSSClient.xcodeproj', force: true)
    push_to_git_remote
  end

  desc 'Runs all the tests'
  lane :test do
    #scan(project: 'RSSClient.xcodeproj', scheme: 'RSSClient')
    sh("bundle exec rake test:ios:app")
    sh("bundle exec rake test:ios:kit")
  end

  lane :test_app do
    scan(scheme: 'RSSClientTests')
  end

  lane :test_kit do
    scan(scheme: 'rNewsKitTests')
  end

  lane :test_acceptance do
    scan(scheme: 'rNewsAcceptanceTests')
  end

  desc 'set up CI to deploy'
  lane :deploy_setup do
    sh 'echo "$MIXPANEL_TOKEN" > .mixpanel'
    sh 'echo "$PASIPHAE_TOKEN" > .pasiphae'
    sh 'echo "$PASIPHAE_URL" > .pasiphaeURL'
  end

  desc 'Deploy a new version to TestFlight'
  lane :deploy_testflight do
    build_number = `git rev-list $(git rev-parse --abbrev-ref HEAD) | wc -l | awk '{ print $1 }'`
    increment_build_number(xcodeproj: 'RSSClient.xcodeproj', build_number: build_number)
    gym(project: 'RSSClient.xcodeproj', scheme: "RSSClient")
    pilot(distribute_external: false, changelog: `git log -1 --format='%B'`)
  end

  desc 'Deploy a new version to the App Store'
  lane :deploy_app_store do
    tracker_release = next_tracker_release

    update_release_notes tracker_release[:release_notes]
    bump_release_version tracker_release[:title]

    add_git_tag(tag: tracker_release[:title])
    push_to_git_remote

    sh 'SNAPSHOT_FORCE_DELETE=1 bundle exec snapshot reset_simulators'
    snapshot

    gym(scheme: "RSSClient")
    deliver

    upload_github_release tracker_release[:title] tracker_release[:release_notes]
  end

  def next_tracker_release
    require 'pivotal-tracker'
    TRACKER_TOKEN = ENV['TRACKER_TOKEN']
    TRACKER_PROJECT_ID = '1423142'

    PivotalTracker::Client.token = TRACKER_TOKEN
    PivotalTracker::Client.use_ssl = true
    project = PivotalTracker::Project.find(TRACKER_PROJECT_ID)
    next_release = project.stories.all(story_type: ['release']).first

    {title: next_release.name, release_notes: next_release.description, story: next_release}
  end

  def update_release_notes(release_notes)
    IO.write('fastlane/metadata/en-US/release_notes.txt', release_notes)
    sh 'git add fastlane/metadata/en-US/release_notes.txt'
  end

  def bump_release_version(tag_name)
    release_version = tag_name.sub(/^v/, '')

    increment_version_number(xcodeproj: 'RSSClient.xcodeproj', version_number: release_version)
    commit_version_bump(xcodeproj: 'RSSClient.xcodeproj', force: true)
  end

  def upload_github_release(tag_name, release_notes)
    set_github_release(
      repository_name: "younata/rssclient",
      api_token: ENV["GITHUB_TOKEN"],
      name: tag_name,
      tag_name: tag_name,
      description: release_notes,
    )
  end
end




# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
