# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.51.0"

default_platform :ios


platform :ios do
  desc 'Pushes'
  lane :push do
    increment_build_number(xcodeproj: 'RSSClient.xcodeproj')
    commit_version_bump(xcodeproj: 'RSSClient.xcodeproj', force: true)
    push_to_git_remote
  end

  desc 'Runs all the tests'
  lane :test do
    #scan(project: 'RSSClient.xcodeproj', scheme: 'RSSClient')
    sh("bundle exec rake test:ios:app")
    sh("bundle exec rake test:ios:kit")
  end

  lane :test_app do
    scan(scheme: 'RSSClientTests')
  end

  lane :test_kit do
    scan(scheme: 'rNewsKitTests')
  end

  lane :test_acceptance do
    scan(scheme: 'rNewsAcceptanceTests')
  end

  desc 'Deploy a new version to TestFlight'
  lane :deploy_testflight do
    increment_build_number(xcodeproj: 'RSSClient.xcodeproj')
    commit_version_bump(xcodeproj: 'RSSClient.xcodeproj', force: true)
    gym(project: 'RSSClient.xcodeproj', scheme: "RSSClient")
    pilot(distribute_external: true, changelog: `git log -1 --format='%B'`)
  end

  desc 'Deploy a new version to the App Store'
  lane :deploy_app_store do
    sh 'bundle exec rake release:publish'
    sh 'SNAPSHOT_FORCE_DELETE=1 snapshot reset_simulators'
    snapshot
    gym(scheme: "RSSClient")
    deliver
    increment_version_number(xcodeproj: 'RSSClient.xcodeproj')
    commit_version_bump(xcodeproj: 'RSSClient.xcodeproj')
    push_to_git_remote
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
