# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5s",
  "iPhone 4s",
  "iPad Retina"
])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme "rNewsAcceptanceTests"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

reinstall_app true
clean true

# Choose which project/workspace to use
project "./RSSClient.xcodeproj"
