import rNews
import rNewsKit

import Foundation

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

class FakeNotificationHandler : NotificationHandler {
    init() {
    }

    private(set) var enableNotificationsCallCount : Int = 0
    private var enableNotificationsArgs : Array<(LocalNotificationSource)> = []
    func enableNotificationsArgsForCall(callIndex: Int) -> (LocalNotificationSource) {
        return self.enableNotificationsArgs[callIndex]
    }
    func enableNotifications(notificationSource: LocalNotificationSource) {
        self.enableNotificationsCallCount += 1
        self.enableNotificationsArgs.append((notificationSource))
    }

    private(set) var handleLocalNotificationCallCount : Int = 0
    private var handleLocalNotificationArgs : Array<(UILocalNotification, UIWindow)> = []
    func handleLocalNotificationArgsForCall(callIndex: Int) -> (UILocalNotification, UIWindow) {
        return self.handleLocalNotificationArgs[callIndex]
    }
    func handleLocalNotification(notification: UILocalNotification, window: UIWindow) {
        self.handleLocalNotificationCallCount += 1
        self.handleLocalNotificationArgs.append((notification, window))
    }

    private(set) var handleActionCallCount : Int = 0
    private var handleActionArgs : Array<(String?, UILocalNotification)> = []
    func handleActionArgsForCall(callIndex: Int) -> (String?, UILocalNotification) {
        return self.handleActionArgs[callIndex]
    }
    func handleAction(identifier: String?, notification: UILocalNotification) {
        self.handleActionCallCount += 1
        self.handleActionArgs.append((identifier, notification))
    }

    private(set) var sendLocalNotificationCallCount : Int = 0
    private var sendLocalNotificationArgs : Array<(LocalNotificationSource, Article)> = []
    func sendLocalNotificationArgsForCall(callIndex: Int) -> (LocalNotificationSource, Article) {
        return self.sendLocalNotificationArgs[callIndex]
    }
    func sendLocalNotification(notificationSource: LocalNotificationSource, article: Article) {
        self.sendLocalNotificationCallCount += 1
        self.sendLocalNotificationArgs.append((notificationSource, article))
    }

    static func reset() {
    }
}
